/* 6430ec29f4f7bd4d4a8948e9c90d983ace649825
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type UserQueryVariables = Types.Exact<{
  id: Types.Scalars['ID'];
}>;
export type UserQuery = {
  __typename?: 'Query';
  getUser?: {
    __typename?: 'User';
    id: string;
    name: string;
  } | null;
};
export declare const UserDocument: DocumentNode<UserQuery, Types.Exact<{
  id: Types.Scalars['ID'];
}>>;